### ISSUE TITLE
Documentation Milestone #1

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/SCRTSibyl-Oracle#23]
#### Documentation
Document the algorithm. Make it understandable and viable for the user.

#### Tasks
  - [x] in line doc in .py files
  - [x] GitHub README.md file for Repo landing page
  - [x] infographics displaying the algorithm flow
  - [x] Score-to-money fuel gauge diagram 
  - [x] Prep Milestone #1 slide presentation + demo for Yonatan Erez and the SCRT Labs team
