### ISSUE TITLE
Deploy on Heroku

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/SCRTSibyl-Oracle#33]
### Summary
Integrate the credit score API. 

### Tasks
 - [x] create a `staging` and `production` app on **Heroku**
 - [x] set up **Heroku** `procfile`, `requirements` and `env vars`
 - [x] test endpoints on **Postman**
   - [x] Plaid
   - [x] Coinbase
