### ISSUE TITLE
Documentation Milestone #2

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/SCRTSibyl-Oracle#36]
#### Description
Explain the algorithm for a specific target audience: users interacting with the SCRTSibyl UI Web app. 

#### Required fields
 - [x] metric captions for the donut charts featured in the Web app landing page
 - [x] legend for the nonlinear score scale and its associated bins of USD amount the user qualified for
 - [x] draft application for SCRTSibyl_phase2 grant
