### ISSUE TITLE
Alter Score Message

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/SCRTSibyl-Oracle#46]
#### Objective
Alter the content, syntax, and parameters included in the UI message returned to the user to explicate their credit score. 

#### Tasks breakdown
 - [x] USD amount must have format $ X,XXX USD
 - [x] USD to SCRT live-conversion --> loan amount in SCRT
 - [x] return field 'bank' displaying the Plaid bank name
 - [x] return comma separated list of algorithm metrics where an error occurred
 - [x] test in production (front end)

#### Front end
 - [x] add pop-up window containing tips on how to improve both the Plaid and the Coinbase score
